StringTable {
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{65E9056CD656C926}" {
   Id "SPC-Magazine_2A46_APFSDS_15_Description"
   Target_en_us "Ammo rack loaded with 3BM29 armor piercing discarding sabot fin stabilized rounds."
   Modified 1709774629
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{65E9056CD3B20067}" {
   Id "SPC-Magazine_2A46_APFSDS_15_Name"
   Target_en_us "125×48mm 15rnd 2A46 APFSDS Rounds"
   Modified 1709774621
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64856C5E017285D7}" {
   Id "SPC-Magazine_2A46_APFSDS_Description"
   Target_en_us "Ammo rack loaded with 3BM15 armor piercing discarding sabot fin stabilized rounds."
   Modified 1686467741
   Author "thoma"
   LastChanged "thoma"
  }
  CustomStringTableItem "{64856C5E05E10457}" {
   Id "SPC-Magazine_2A46_APFSDS_Name"
   Target_en_us "125×48mm 20rnd 2A46 APFSDS Rounds"
   Modified 1686467368
   Author "thoma"
   LastChanged "thoma"
  }
  CustomStringTableItem "{65E9056D44972D7B}" {
   Id "SPC-Magazine_2A46_HE_22_Description"
   Target_en_us "Ammo rack loaded with 3OF26 high explosive fragmentation fin stabilized rounds."
   Modified 1709774413
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{65E9056D5FFB0DE4}" {
   Id "SPC-Magazine_2A46_HE_22_Name"
   Target_en_us "125×48mm 22rnd 2A46 HE-FRAG-FS Rounds"
   Modified 1709774380
   Author "mikia"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64856C5E7C174C30}" {
   Id "SPC-Magazine_2A46_HE_Description"
   Target_en_us "Ammo rack loaded with 3OF26 high explosive fragmentation fin stabilized rounds."
   Modified 1686467475
   Author "thoma"
   LastChanged "thoma"
  }
  CustomStringTableItem "{64856C5E70F57A24}" {
   Id "SPC-Magazine_2A46_HE_Name"
   Target_en_us "125×48mm 20rnd 2A46 HE-FRAG-FS Rounds"
   Modified 1686467339
   Author "thoma"
   LastChanged "thoma"
  }
  CustomStringTableItem "{64856C5E176C493D}" {
   Id "SPC-Magazine_2A46_HEATFS_Description"
   Target_en_us "Ammo rack loaded with 3BK18M high explosive anti-tank fin stabilized rounds."
   Modified 1709771271
   Author "thoma"
   LastChanged "mikia"
  }
  CustomStringTableItem "{64856C5E2B74927D}" {
   Id "SPC-Magazine_2A46_HEATFS_Name"
   Target_en_us "125×48mm 7rnd 2A46 HEAT-FS Rounds"
   Modified 1709774435
   Author "thoma"
   LastChanged "mikia"
  }
  CustomStringTableItem "{60F284C34C2BF591}" {
   Id "SPC-Vehicle_T72A_Name"
   Target_en_us "T-72A Main Battle Tank"
   Modified 1626510298
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
  CustomStringTableItem "{60F284C3516FCDD0}" {
   Id "SPC-Vehicle_T72B_Name"
   Target_en_us "T-72B Main Battle Tank"
   Modified 1626510296
   Author "Ethan Benzel"
   LastChanged "Ethan Benzel"
  }
 }
}